version: '3.8'
services:
  app:
    container_name: ft-comprasplus
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"